# Generated by Django 4.2 on 2023-05-03 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("second_brain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("P", "Physical"),
                            ("M", "Mental"),
                            ("S", "Spiritual"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")],
                        max_length=1,
                    ),
                ),
                ("completion_count", models.PositiveIntegerField()),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
