# Generated by Django 4.2 on 2023-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_goal",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of times the task should be completed in a week/month for weekly/monthly tasks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times the task has been completed"
            ),
        ),
    ]
