# Generated by Django 4.2 on 2023-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0003_task_completion_goal_alter_task_completion_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completion_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_goal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
