# Generated by Django 4.2.1 on 2023-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0007_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
