# Generated by Django 4.2.1 on 2023-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0008_task_last_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
