# Generated by Django 4.2.1 on 2023-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0010_passion_passionactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("R", "Routine"),
                    ("P", "Physical"),
                    ("M", "Mental"),
                    ("S", "Spiritual"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_goal",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="taskhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("R", "Routine"),
                    ("P", "Physical"),
                    ("M", "Mental"),
                    ("S", "Spiritual"),
                ],
                max_length=1,
            ),
        ),
    ]
