# Generated by Django 4.2.1 on 2023-05-20 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "second_brain",
            "0011_alter_task_category_alter_task_completion_goal_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completion_count",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completion_goal",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="completion_count",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="completion_goal",
        ),
    ]
