# Generated by Django 4.2.1 on 2023-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0013_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
