# Generated by Django 4.2.2 on 2023-08-02 19:40

from django.db import migrations, models
import django.db.models.deletion

def create_default_categories(apps, schema_editor):
    PassionCategory = apps.get_model('second_brain', 'PassionCategory')
    PassionCategory.objects.create(name="Physical")
    PassionCategory.objects.create(name="Mental")
    PassionCategory.objects.create(name="Spiritual")

class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0016_remove_quoteoftheday_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="passion",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="second_brain.passioncategory",
            ),
        ),
        migrations.RunPython(create_default_categories),
    ]