# Generated by Django 4.2.2 on 2023-08-12 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0017_passioncategory_passion_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="passionactivity",
            unique_together={("passion", "date")},
        ),
    ]
