# Generated by Django 4.2.2 on 2023-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0018_alter_passionactivity_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="passion",
            name="color",
            field=models.CharField(default="#808080", max_length=7),
        ),
    ]
