# Generated by Django 4.2.4 on 2023-10-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("second_brain", "0019_passion_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_reset_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
