# Generated by Django 4.2.4 on 2023-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
