# Generated by Django 4.2.4 on 2023-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
