# Generated by Django 4.2.4 on 2023-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_payment_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="update_payment_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
