# Generated by Django 4.2.4 on 2023-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_payment_update_payment_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="update_payment_url",
        ),
    ]
